# Generated by Django 2.2 on 2021-06-01 16:53

import app_comments.models
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_user', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=500, verbose_name='评论内容')),
                ('uuid', models.CharField(default=app_comments.models.uuid4_hex, editable=False, max_length=32, unique=True, verbose_name='唯一标识')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP地址')),
                ('is_overhead', models.BooleanField(default=False, verbose_name='是否顶置')),
                ('is_hide', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('object_id', models.PositiveIntegerField(verbose_name='关联对象ID')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mp_comments', to='app_user.UserProfile', verbose_name='评论作者')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('article', 'photo')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='关联对象类型')),
                ('parent_comment', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='app_comments.MpComments', verbose_name='上级评论')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', mdeditor.fields.MDTextField(verbose_name='评论内容')),
                ('uuid', models.CharField(default=app_comments.models.uuid4_hex, editable=False, max_length=32, unique=True, verbose_name='唯一标识')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP地址')),
                ('is_overhead', models.BooleanField(default=False, verbose_name='是否顶置')),
                ('is_hide', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('object_id', models.PositiveIntegerField(verbose_name='关联对象ID')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_user.UserProfile', verbose_name='评论作者')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('article', 'photo')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='关联对象类型')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='app_comments.Comments', verbose_name='上级评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ('-is_overhead', '-created_time'),
            },
        ),
    ]
