# Generated by Django 2.2 on 2021-05-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='is_active',
        ),
        migrations.AddField(
            model_name='comments',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='是否可见'),
        ),
    ]
