# Generated by Django 2.2 on 2021-05-26 12:33

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-is_overhead', '-created_time'), 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.RemoveField(
            model_name='comments',
            name='last_mod_time',
        ),
        migrations.AlterField(
            model_name='comments',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='mpcomments',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='mpcomments',
            name='parent_comment',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comments', to='app_comments.MpComments', verbose_name='上级评论'),
        ),
    ]
