# Generated by Django 2.2 on 2021-05-27 08:56

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0002_auto_20210526_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=mdeditor.fields.MDTextField(verbose_name='评论内容'),
        ),
    ]
