# Generated by Django 2.2 on 2021-05-17 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0002_auto_20210517_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('article', 'photo')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='关联对象类型'),
        ),
    ]
