# Generated by Django 2.2 on 2021-05-17 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0005_auto_20210517_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wanderer',
            old_name='nickname',
            new_name='username',
        ),
    ]
