# Generated by Django 2.2 on 2021-05-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0007_auto_20210517_2206'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comments',
            constraint=models.CheckConstraint(check=models.Q(('author__isnull', False), ('wanderer__isnull', False), _connector='OR'), name='exist_user_or_wanderer'),
        ),
    ]
