# Generated by Django 2.2 on 2021-05-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0008_auto_20210517_2225'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comments',
            name='exist_user_or_wanderer',
        ),
        migrations.AddConstraint(
            model_name='comments',
            constraint=models.CheckConstraint(check=models.Q(('author__isnull', False), ('wanderer__isnull', False), _connector='OR'), name='User 或 Wanderer 必须存在其中一个!'),
        ),
    ]
