# Generated by Django 2.2 on 2021-05-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0009_auto_20210517_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(max_length=500, verbose_name='评论内容'),
        ),
    ]
