# Generated by Django 2.2 on 2021-05-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0010_auto_20210517_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='is_overhead',
            field=models.BooleanField(default=False, verbose_name='是否顶置'),
        ),
    ]
