# Generated by Django 2.2 on 2021-05-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0011_comments_is_overhead'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comments',
            name='User 或 Wanderer 必须存在其中一个!',
        ),
        migrations.AddConstraint(
            model_name='comments',
            constraint=models.CheckConstraint(check=models.Q(('author__isnull', False), ('wanderer__isnull', False), _connector='OR'), name='User 或 Wanderer 至少存在其中一个!'),
        ),
    ]
