# Generated by Django 2.2 on 2021-05-19 15:34

import app_comments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0014_auto_20210519_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='uuid',
            field=models.UUIDField(default=app_comments.models.uuid4_hex, editable=False, unique=True, verbose_name='唯一标识'),
        ),
    ]
