# Generated by Django 2.2 on 2021-05-19 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0016_auto_20210519_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='wanderer',
            field=models.ForeignKey(blank=True, help_text='当作者(Author)和散人(Wanderer)同时存在时,置wanderer=None', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_comments.Wanderer', verbose_name='散人'),
        ),
    ]
