# Generated by Django 2.2 on 2021-05-19 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0017_auto_20210519_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='wanderer',
            field=models.ForeignKey(blank=True, help_text='当作者(Author)和散人(Wanderer)同时设置时,置Wanderer=None', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_comments.Wanderer', verbose_name='散人'),
        ),
    ]
