# Generated by Django 2.2 on 2021-05-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0019_auto_20210521_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-is_overhead', '-last_mod_time'), 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
