# Generated by Django 2.2 on 2021-05-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0020_auto_20210521_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='comments',
            name='is_hide',
            field=models.BooleanField(default=False, verbose_name='是否可见'),
        ),
    ]
