# Generated by Django 2.2 on 2021-05-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0021_auto_20210521_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='is_hide',
            field=models.BooleanField(default=False, verbose_name='是否隐藏'),
        ),
    ]
