# Generated by Django 2.2 on 2021-05-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0022_auto_20210521_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP 地址'),
        ),
    ]
