# Generated by Django 2.2 on 2021-05-24 10:22

import app_comments.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_comments', '0023_comments_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=500, verbose_name='评论内容')),
                ('uuid', models.CharField(default=app_comments.models.uuid4_hex, editable=False, max_length=32, unique=True, verbose_name='唯一标识')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP 地址')),
                ('is_overhead', models.BooleanField(default=False, verbose_name='是否顶置')),
                ('is_hide', models.BooleanField(default=False, verbose_name='是否隐藏')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('object_id', models.PositiveIntegerField(verbose_name='关联对象ID')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mp_comments', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('article', 'photo')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='关联对象类型')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app_comments.MpComments', verbose_name='上级评论')),
                ('wanderer', models.ForeignKey(blank=True, help_text='当作者(Author)和散人(Wanderer)同时设置时,置Wanderer=None', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mp_comments', to='app_comments.Wanderer', verbose_name='散人')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
