# Generated by Django 2.2 on 2021-05-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0024_mpcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mpcomments',
            old_name='parent',
            new_name='parent_comment',
        ),
    ]
