# Generated by Django 2.2 on 2021-05-25 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_comments', '0025_auto_20210525_0833'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comments',
            name='User 或 Wanderer 至少存在其中一个!',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='wanderer',
        ),
        migrations.RemoveField(
            model_name='mpcomments',
            name='wanderer',
        ),
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_user.UserProfile', verbose_name='评论作者'),
        ),
        migrations.AlterField(
            model_name='mpcomments',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mp_comments', to='app_user.UserProfile', verbose_name='评论作者'),
        ),
        migrations.DeleteModel(
            name='Wanderer',
        ),
    ]
