# Generated by Django 2.2 on 2021-04-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_userprofile_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='org',
        ),
    ]
