# Generated by Django 2.2 on 2020-12-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_auto_20201230_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, verbose_name='slug'),
        ),
    ]
