# Generated by Django 2.2 on 2020-12-30 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0006_auto_20201230_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='app_blog.Category', verbose_name='分类'),
        ),
    ]
