# Generated by Django 2.2 on 2020-12-30 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0008_auto_20201230_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='发布时间'),
        ),
    ]
