# Generated by Django 2.2 on 2020-12-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='最近修改'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='org',
            field=models.CharField(blank=True, max_length=128, verbose_name='组织'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, verbose_name='手机号'),
        ),
    ]
