# Generated by Django 2.2 on 2021-01-08 17:34

import app_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='users/default.png', upload_to=app_user.models.user_directory_path, verbose_name='头像'),
        ),
    ]
