# Generated by Django 2.2 on 2020-12-23 10:05

import app_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_auto_20201215_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='users/default.jpeg', upload_to=app_user.models.user_directory_path, verbose_name='头像'),
        ),
    ]
