# Generated by Django 2.2 on 2021-06-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0002_filestorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='文件'),
        ),
    ]
