# Generated by Django 2.2 on 2021-06-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0003_auto_20210621_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='sitelogo',
            field=models.ImageField(default='set_settings/logo/default.png', upload_to='set_settings/logo/%Y%m%d/', verbose_name='网站logo'),
        ),
    ]
