# Generated by Django 2.2 on 2021-06-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0003_auto_20210615_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorage',
            name='file',
            field=models.FileField(default='', upload_to='uploads/%Y/%m/%d/', verbose_name='文件'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='文件名'),
        ),
    ]
