# Generated by Django 2.2 on 2021-06-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0005_auto_20210615_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorage',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='文件名'),
        ),
    ]
