# Generated by Django 2.2.27 on 2022-03-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0005_auto_20210621_1720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutBlog',
        ),
        migrations.DeleteModel(
            name='Silian',
        ),
    ]
