# Generated by Django 2.2 on 2021-06-15 11:02

import app_common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0006_auto_20210615_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorage',
            name='file',
            field=models.FileField(upload_to=app_common.models.file_path, verbose_name='文件'),
        ),
    ]
