# Generated by Django 2.2 on 2021-06-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0007_auto_20210615_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorage',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
    ]
