# Generated by Django 2.2 on 2021-06-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0008_filestorage_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorage',
            name='size',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='文件大小'),
        ),
    ]
