# Generated by Django 2.2 on 2021-06-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_common', '0009_filestorage_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorage',
            name='size',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, verbose_name='文件大小'),
        ),
    ]
