# Generated by Django 2.2 on 2021-06-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='正文')),
                ('img', models.ImageField(blank=True, upload_to='diary', verbose_name='图片')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('mood', models.CharField(choices=[('shy', '害羞🥰'), ('hehe', '呵呵🙂'), ('smug', '得意🤪'), ('happy', '高兴😆'), ('anger', '愤怒😡'), ('lonely', '寂寞😶'), ('nervous', '紧张😅'), ('anxiety', '焦虑😞'), ('annoyed', '恼怒😤'), ('confused', '困惑🤯'), ('disgusted', '厌恶🤮'), ('embarassed', '尴尬🥴'), ('exhausted', '精疲力尽😵')], default='happy', max_length=15, verbose_name='心情')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '日记',
                'verbose_name_plural': '日记',
                'ordering': ('-created',),
            },
        ),
    ]
