# Generated by Django 2.2.27 on 2022-03-10 18:30

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='img',
        ),
        migrations.AlterField(
            model_name='diary',
            name='body',
            field=mdeditor.fields.MDTextField(verbose_name='正文'),
        ),
    ]
