# Generated by Django 2.2 on 2021-06-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diary', '0002_auto_20210604_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='mood',
            field=models.CharField(choices=[('shy', '害羞🥰'), ('hehe', '呵呵🙂'), ('smug', '得意🤪'), ('happy', '高兴😆'), ('anger', '愤怒😡'), ('lonely', '寂寞😶'), ('nervous', '紧张😅'), ('anxiety', '焦虑😞'), ('annoyed', '恼怒😤'), ('confused', '困惑🤯'), ('disgusted', '厌恶🤮'), ('embarassed', '尴尬🥴'), ('exhausted', '精疲力尽😵')], default='happy', max_length=15, verbose_name='心情'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug'),
        ),
    ]
