# Generated by Django 2.2 on 2021-06-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_diary', '0003_auto_20210604_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='img',
            field=models.ImageField(blank=True, upload_to='diary', verbose_name='图片'),
        ),
    ]
