# Generated by Django 2.2 on 2021-06-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_diary', '0004_diary_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ('-created',), 'verbose_name': '日记', 'verbose_name_plural': '日记'},
        ),
    ]
