# Generated by Django 2.2 on 2021-06-21 08:35

import app_common.models
import app_gallery.models
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import myweb.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=app_common.models.uuid4_hex, editable=False, max_length=10, unique=True, verbose_name='唯一标识')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='相册名称')),
                ('thumb', imagekit.models.fields.ProcessedImageField(upload_to=app_gallery.models.gallery_directory_path, verbose_name='缩略图')),
                ('is_delete', models.BooleanField(default=False, verbose_name='已删除')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否可见')),
            ],
            options={
                'verbose_name': '相册',
                'verbose_name_plural': '相册',
                'ordering': ('-last_mod_time',),
            },
            bases=(models.Model, myweb.utils.AdminMixin),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app_gallery.models.photo_directory_path, verbose_name='图片')),
                ('thumb', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=app_gallery.models.thumb_directory_path, verbose_name='缩略图')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('is_delete', models.BooleanField(default=False, verbose_name='已删除')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos', to='app_gallery.Gallery', verbose_name='所属相册')),
            ],
            options={
                'verbose_name': '相片',
                'verbose_name_plural': '相片',
                'ordering': ('-create_date',),
            },
            bases=(models.Model, myweb.utils.AdminMixin),
        ),
    ]
