# Generated by Django 2.2 on 2021-05-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=100, verbose_name='相册名称'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
    ]
