# Generated by Django 2.2 on 2021-05-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gallery', '0002_auto_20210517_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='alt',
            new_name='title',
        ),
    ]
