# Generated by Django 2.2 on 2021-06-01 17:51

import app_gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gallery', '0003_remove_gallery_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=app_gallery.models.gallery_directory_path, verbose_name='图片'),
        ),
    ]
