# Generated by Django 2.2 on 2021-06-01 17:54

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_gallery', '0004_auto_20210601_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(upload_to='gallery', verbose_name='缩略图'),
        ),
    ]
