# Generated by Django 2.2 on 2021-06-01 17:58

import app_gallery.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_gallery', '0005_auto_20210601_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(upload_to=app_gallery.models.gallery_directory_path, verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=app_gallery.models.photo_directory_path, verbose_name='图片'),
        ),
    ]
