# Generated by Django 2.2 on 2021-06-01 18:12

import app_gallery.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_gallery', '0006_auto_20210601_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=app_gallery.models.thumb_directory_path, verbose_name='缩略图'),
        ),
    ]
