# Generated by Django 2.2 on 2021-02-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_auto_20210217_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_link',
            field=models.CharField(default='/static/blog/img/summary.png', max_length=255, verbose_name='图片地址'),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(default='文章摘要等同于网页description内容，请务必填写...', max_length=230, verbose_name='文章摘要'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, unique_for_date='pub_time', verbose_name='slug'),
        ),
    ]
