# Generated by Django 2.2 on 2021-02-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_auto_20210222_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_link',
            field=models.CharField(default='/static/app_blog/images/occupying.png', max_length=255, verbose_name='图片地址'),
        ),
    ]
