# Generated by Django 2.2 on 2020-12-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gallery', '0002_auto_20201223_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('-mod_date',), 'verbose_name': '相册', 'verbose_name_plural': '相册'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-create_date',), 'verbose_name': '相片', 'verbose_name_plural': '相片'},
        ),
    ]
