# Generated by Django 2.2 on 2021-05-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment_status',
            field=models.BooleanField(default=True, verbose_name='是否开启评论'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否隐藏'),
        ),
    ]
