# Generated by Django 2.2 on 2021-06-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(max_length=300, verbose_name='文章摘要'),
        ),
    ]
