# Generated by Django 2.2 on 2021-06-18 18:05

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_auto_20210618_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='app_blog.CnTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
