# Generated by Django 2.2 on 2021-05-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_auto_20210515_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cntag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
    ]
