# Generated by Django 2.2 on 2021-05-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_auto_20210517_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_order',
            field=models.IntegerField(blank=True, default=0, verbose_name='排序,数字越大越靠前'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='阅读次数'),
        ),
    ]
