# Generated by Django 2.2 on 2021-02-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_auto_20210222_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img_link',
            field=models.CharField(default='/static/app_blog/images/summary.png', max_length=255, verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='article_sub_length',
            field=models.IntegerField(default=100, verbose_name='文章摘要长度'),
        ),
    ]
