# Generated by Django 2.2 on 2021-02-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0006_auto_20210222_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(default='文章摘要等同于网页description内容，请务必填写...', max_length=300, verbose_name='文章摘要'),
        ),
    ]
