# Generated by Django 2.2 on 2021-05-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0007_auto_20210223_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsettings',
            name='allow_register',
            field=models.BooleanField(default=False, verbose_name='是否允许用户注册'),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='analyticscode',
            field=models.TextField(blank=True, default='', max_length=1000, verbose_name='网站统计代码'),
        ),
    ]
