# Generated by Django 2.2 on 2021-05-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0008_auto_20210507_0839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogSettings',
        ),
    ]
