# Generated by Django 2.2 on 2021-05-07 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0009_delete_blogsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutBlog',
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
        migrations.DeleteModel(
            name='FriendLink',
        ),
        migrations.DeleteModel(
            name='Silian',
        ),
    ]
