# Generated by Django 2.2 on 2021-05-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0010_auto_20210507_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': '文章分类', 'verbose_name_plural': '文章分类'},
        ),
    ]
