# Generated by Django 2.2 on 2021-05-26 08:20

import app_user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=app_user.models.user_directory_path, verbose_name='头像')),
                ('telephone', models.CharField(blank=True, max_length=50, null=True, verbose_name='手机号')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='个人简介')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('w_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='昵称(游民)')),
                ('w_email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='邮箱(游民)')),
                ('is_wanderer', models.BooleanField(default=False, verbose_name='是否是游民')),
                ('uuid', models.CharField(default=app_user.models.uuid4_hex, editable=False, max_length=10, unique=True, verbose_name='唯一标识')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='关联的用户信息')),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='app_user.Recipe')),
            ],
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(fields=('telephone',), name='unique_phone'),
        ),
    ]
