# Generated by Django 2.2 on 2021-04-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='个人简介'),
        ),
    ]
