# Generated by Django 2.2 on 2021-05-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='修改日期'),
        ),
    ]
