# Generated by Django 2.2 on 2021-05-25 22:56

import app_user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_auto_20210516_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_wanderer',
            field=models.BooleanField(default=False, verbose_name='是否是游民'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='w_email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='邮箱(游民)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='w_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='昵称(游民)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=app_user.models.user_directory_path, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='关联的用户信息'),
        ),
    ]
