# Generated by Django 2.2 on 2021-05-25 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_userprofile_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='uuid',
        ),
    ]
